### ISSUE TITLE
Add OP Support

### ISSUE THREAD

**Issue by ABMNBLSNWMN** [thenamespace/namespace-sdk#3]

**Comment by nenadmitt** [comment]
Add optimism deployment addresses to namespace sdk https://github.com/thenamespace/namespace-sdk/commit/c42b66e16fe33ba172d68fb9efbeab2658c578e0

**Comment by nenadmitt** [comment]
Op contracts added https://github.com/thenamespace/namespace-sdk/commit/c42b66e16fe33ba172d68fb9efbeab2658c578e0
